#!/usr/bin/env bash
# Generates every richimg APNG test fixture and its reference frames, so
# `cargo test -p richimg` needs no image tool at run time (only at fixture
# generation time, i.e. when this script is re-run after a deliberate
# change). Re-running it is idempotent: it recreates every generated file
# from scratch in a throwaway temp directory and only then copies the
# results over the committed ones. Sibling of `make.sh` (WebP); this one
# owns `tests/fixtures/apng/**` only and never touches `make.sh`'s files.
#
# Every APNG fixture is hand-assembled byte-for-byte in python3 (struct +
# zlib + crc32): real encoders (`ffmpeg -f apng`, `magick`) choose their own
# dispose/blend ops and never emit a "default image that is not a frame", so
# there is no tool that can produce the specific `fcTL` fields these tests
# need to pin. References are raw RGBA8 from ffmpeg's own (independent)
# APNG decoder, which composites internally before the `rawvideo` mux —
# never generated by richimg's own code.
set -euo pipefail

FIXTURES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/apng"
REFS_DIR="$FIXTURES_DIR/refs"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

mkdir -p "$FIXTURES_DIR" "$REFS_DIR"
cd "$WORK"

# ---------------------------------------------------------------------------
# The APNG builder. Every fixture below is a call into this module: it
# hand-assembles PNG chunks (IHDR/PLTE/tRNS/acTL/fcTL/IDAT/fdAT/IEND) with
# real CRC32s, giving exact control over every `fcTL` field that no encoder
# exposes (sequence numbers, a leading `fcTL`-less default image, dispose ops
# per frame, etc).
# ---------------------------------------------------------------------------
cat > apnglib.py <<'PY'
import struct
import zlib

PNG_SIGNATURE = bytes([137, 80, 78, 71, 13, 10, 26, 10])

# APNG spec dispose/blend op codes (https://wiki.mozilla.org/APNG_Specification).
DISPOSE_NONE, DISPOSE_BACKGROUND, DISPOSE_PREVIOUS = 0, 1, 2
BLEND_SOURCE, BLEND_OVER = 0, 1

# PNG IHDR color types.
COLOR_GRAYSCALE, COLOR_RGB, COLOR_INDEXED, COLOR_GRAYSCALE_ALPHA, COLOR_RGBA = 0, 2, 3, 4, 6


def chunk(tag, data):
    body = tag + data
    return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)


def ihdr(width, height, bit_depth, color_type):
    return chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, bit_depth, color_type, 0, 0, 0))


def plte(entries):
    """`entries`: list of (r, g, b)."""
    return chunk(b"PLTE", b"".join(struct.pack(">BBB", r, g, b) for r, g, b in entries))


def trns(alphas):
    """`alphas`: list of per-palette-entry alpha bytes."""
    return chunk(b"tRNS", bytes(alphas))


def actl(num_frames, num_plays):
    return chunk(b"acTL", struct.pack(">II", num_frames, num_plays))


def fctl(seq, width, height, x_offset, y_offset, delay_num, delay_den, dispose_op, blend_op):
    return chunk(
        b"fcTL",
        struct.pack(
            ">IIIIIHHBB",
            seq, width, height, x_offset, y_offset, delay_num, delay_den, dispose_op, blend_op,
        ),
    )


def idat(scanlines):
    return chunk(b"IDAT", zlib.compress(scanlines, 9))


def fdat(seq, scanlines):
    return chunk(b"fdAT", struct.pack(">I", seq) + zlib.compress(scanlines, 9))


def iend():
    return chunk(b"IEND", b"")


def scanlines_rgba8(pixels, width, height):
    """`pixels`: row-major list of (r, g, b, a), filter type None on every row."""
    out = bytearray()
    for y in range(height):
        out.append(0)
        for x in range(width):
            r, g, b, a = pixels[y * width + x]
            out += bytes([r, g, b, a])
    return bytes(out)


def scanlines_rgb8(pixels, width, height):
    out = bytearray()
    for y in range(height):
        out.append(0)
        for x in range(width):
            r, g, b = pixels[y * width + x]
            out += bytes([r, g, b])
    return bytes(out)


def scanlines_rgba16(pixels, width, height):
    """`pixels`: row-major list of (r, g, b, a) 16-bit big-endian values."""
    out = bytearray()
    for y in range(height):
        out.append(0)
        for x in range(width):
            r, g, b, a = pixels[y * width + x]
            out += struct.pack(">HHHH", r, g, b, a)
    return bytes(out)


def scanlines_indexed8(indices, width, height):
    out = bytearray()
    for y in range(height):
        out.append(0)
        for x in range(width):
            out.append(indices[y * width + x])
    return bytes(out)


def solid(width, height, pixel):
    return [pixel] * (width * height)


class ApngBuilder:
    """Assembles one APNG file from a sequence of frames, plus an optional
    leading default image that is NOT part of the animation (no `fcTL`
    before `IDAT`)."""

    def __init__(self, width, height, bit_depth=8, color_type=COLOR_RGBA, palette=None, trns_alphas=None):
        self.width = width
        self.height = height
        self.bit_depth = bit_depth
        self.color_type = color_type
        self.palette = palette
        self.trns_alphas = trns_alphas
        self.seq = 0

    def _next_seq(self):
        value = self.seq
        self.seq += 1
        return value

    def build(self, frames, default_image_scanlines=None, num_plays=1):
        """`frames`: list of dicts with keys width, height, x_offset, y_offset,
        delay_num, delay_den, dispose_op, blend_op, scanlines.
        `default_image_scanlines`: if given, becomes the `IDAT` payload with
        NO preceding `fcTL` (a non-animated default image); frame 0's own
        `fcTL`+`fdAT` follow. If omitted, frame 0's `fcTL` precedes `IDAT`
        (`IDAT` itself is frame 0).
        """
        out = bytearray()
        out += PNG_SIGNATURE
        out += ihdr(self.width, self.height, self.bit_depth, self.color_type)
        if self.palette is not None:
            out += plte(self.palette)
        if self.trns_alphas is not None:
            out += trns(self.trns_alphas)
        out += actl(len(frames), num_plays)

        if default_image_scanlines is not None:
            out += idat(default_image_scanlines)
            for frame in frames:
                out += fctl(
                    self._next_seq(), frame["width"], frame["height"], frame["x_offset"], frame["y_offset"],
                    frame["delay_num"], frame["delay_den"], frame["dispose_op"], frame["blend_op"],
                )
                out += fdat(self._next_seq(), frame["scanlines"])
        else:
            first = frames[0]
            out += fctl(
                self._next_seq(), first["width"], first["height"], first["x_offset"], first["y_offset"],
                first["delay_num"], first["delay_den"], first["dispose_op"], first["blend_op"],
            )
            out += idat(first["scanlines"])
            for frame in frames[1:]:
                out += fctl(
                    self._next_seq(), frame["width"], frame["height"], frame["x_offset"], frame["y_offset"],
                    frame["delay_num"], frame["delay_den"], frame["dispose_op"], frame["blend_op"],
                )
                out += fdat(self._next_seq(), frame["scanlines"])

        out += iend()
        return bytes(out)


def frame(width, height, x_offset, y_offset, pixels, delay_num=1, delay_den=10,
          dispose_op=DISPOSE_NONE, blend_op=BLEND_SOURCE, encode=scanlines_rgba8):
    return {
        "width": width, "height": height, "x_offset": x_offset, "y_offset": y_offset,
        "delay_num": delay_num, "delay_den": delay_den, "dispose_op": dispose_op, "blend_op": blend_op,
        "scanlines": encode(pixels, width, height),
    }
PY

# ---------------------------------------------------------------------------
# 1: dispose = NONE, three full/partial frames accumulating on the canvas —
# proves NONE leaves everything drawn so far in place (contrast with the
# BACKGROUND fixture below).
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 4
b = ApngBuilder(W, H)
frames = [
    frame(W, H, 0, 0, solid(W, H, (255, 0, 0, 255))),
    frame(2, 2, 0, 0, solid(2, 2, (0, 255, 0, 255))),          # top-left
    frame(2, 2, 2, 2, solid(2, 2, (0, 0, 255, 255))),          # bottom-right, opposite corner
]
open("dispose_none.png", "wb").write(b.build(frames))
PY

# ---------------------------------------------------------------------------
# 2: dispose = BACKGROUND. Frame 0 is full-canvas opaque red with
# dispose=Background; frame 1 covers only the left half, so the right half
# must come out transparent (frame 0's region was cleared before frame 1
# drew), never red.
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W, H = 4, 2
b = ApngBuilder(W, H)
frames = [
    frame(W, H, 0, 0, solid(W, H, (255, 0, 0, 255)), dispose_op=DISPOSE_BACKGROUND),
    frame(2, H, 0, 0, solid(2, H, (0, 255, 0, 255))),
]
open("dispose_background.png", "wb").write(b.build(frames))
PY

# ---------------------------------------------------------------------------
# 3: dispose = PREVIOUS (not on frame 0). Frame 0 establishes a blue
# background (dispose=None). Frame 1 (dispose=Previous) draws green over the
# whole canvas. Frame 2 draws fully-transparent pixels with blend=Over (a
# no-op blend), so what shows must be frame 1's disposal restoring frame 0's
# blue — never green, and never a BACKGROUND-style clear to transparent.
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 4
b = ApngBuilder(W, H)
frames = [
    frame(W, H, 0, 0, solid(W, H, (0, 0, 255, 255))),
    frame(W, H, 0, 0, solid(W, H, (0, 255, 0, 255)), dispose_op=DISPOSE_PREVIOUS),
    frame(W, H, 0, 0, solid(W, H, (0, 0, 0, 0)), blend_op=BLEND_OVER),
]
open("dispose_previous.png", "wb").write(b.build(frames))
PY

# ---------------------------------------------------------------------------
# 4: dispose = PREVIOUS on FRAME 0 specifically. Per the APNG spec this is
# treated as BACKGROUND (there is no prior state), so frame 0's region clears
# to transparent before frame 1 — not "no-op" (which PREVIOUS would otherwise
# be read as, restoring an undefined earlier state).
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 4
b = ApngBuilder(W, H)
frames = [
    frame(W, H, 0, 0, solid(W, H, (255, 0, 0, 255)), dispose_op=DISPOSE_PREVIOUS),
    frame(W, H, 0, 0, solid(W, H, (0, 0, 0, 0)), blend_op=BLEND_OVER),
]
open("dispose_previous_first_frame.png", "wb").write(b.build(frames))
PY

# ---------------------------------------------------------------------------
# 5: blend = SOURCE with a semi-transparent subframe — the region must come
# out as the subframe's OWN straight alpha, never blended with what was
# underneath (contrast with the OVER fixture below).
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 4
b = ApngBuilder(W, H)
frames = [
    frame(W, H, 0, 0, solid(W, H, (0, 0, 255, 255))),
    frame(2, 2, 1, 1, solid(2, 2, (0, 255, 0, 128)), blend_op=BLEND_SOURCE),
]
open("blend_source.png", "wb").write(b.build(frames))
PY

# ---------------------------------------------------------------------------
# 6: blend = OVER with a semi-transparent subframe over an opaque
# destination — the region must show the spec's straight-alpha "over"
# formula, not a straight overwrite.
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 4
b = ApngBuilder(W, H)
frames = [
    frame(W, H, 0, 0, solid(W, H, (0, 0, 255, 255))),
    frame(2, 2, 1, 1, solid(2, 2, (0, 255, 0, 128)), blend_op=BLEND_OVER),
]
open("blend_over.png", "wb").write(b.build(frames))
PY

# ---------------------------------------------------------------------------
# 5b: a "still" APNG — acTL.num_frames == 1, `fcTL` precedes `IDAT` (frame 0
# IS the IDAT). `next_frame` must keep returning frame 0 (index 0) forever.
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 4
b = ApngBuilder(W, H)
frames = [frame(W, H, 0, 0, solid(W, H, (128, 64, 200, 255)))]
open("still.png", "wb").write(b.build(frames))
PY

# ---------------------------------------------------------------------------
# 7: fractional delays — 1/3 s, 7/100 s, and delay_den = 0 (meaning 1/100 s,
# so num=5,den=0 means 50 ms).
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 2
b = ApngBuilder(W, H)
frames = [
    frame(W, H, 0, 0, solid(W, H, (255, 0, 0, 255)), delay_num=1, delay_den=3),
    frame(W, H, 0, 0, solid(W, H, (0, 255, 0, 255)), delay_num=7, delay_den=100),
    frame(W, H, 0, 0, solid(W, H, (0, 0, 255, 255)), delay_num=5, delay_den=0),
]
open("fractional_delays.png", "wb").write(b.build(frames))
PY

# ---------------------------------------------------------------------------
# 8: the delay floor. 0 ms and 10 ms (both under the fixed 20 ms
# SHORT_DELAY_THRESHOLD) must come out as `short_delay_substitute`; 20 ms
# must pass through unchanged.
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 2
b = ApngBuilder(W, H)
frames = [
    frame(W, H, 0, 0, solid(W, H, (255, 0, 0, 255)), delay_num=0, delay_den=1000),
    frame(W, H, 0, 0, solid(W, H, (0, 255, 0, 255)), delay_num=1, delay_den=100),
    frame(W, H, 0, 0, solid(W, H, (0, 0, 255, 255)), delay_num=1, delay_den=50),
]
open("short_delays.png", "wb").write(b.build(frames))
PY

# ---------------------------------------------------------------------------
# 9: a finite loop count (num_plays = 3) and an infinite one (num_plays = 0).
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 2
frames = [
    frame(W, H, 0, 0, solid(W, H, (255, 0, 0, 255))),
    frame(W, H, 0, 0, solid(W, H, (0, 255, 0, 255))),
]
open("loop_finite.png", "wb").write(ApngBuilder(W, H).build(list(frames), num_plays=3))
open("loop_infinite.png", "wb").write(ApngBuilder(W, H).build(list(frames), num_plays=0))
PY

# ---------------------------------------------------------------------------
# 10: a default image that is NOT a frame (no `fcTL` before `IDAT`). The
# default image is a distinctive magenta that must never appear in any
# decoded frame; `frame_count` must be 2 (acTL.num_frames), not 3.
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 4
b = ApngBuilder(W, H)
default_image = scanlines_rgba8(solid(W, H, (255, 0, 255, 255)), W, H)  # distinctive magenta
frames = [
    frame(W, H, 0, 0, solid(W, H, (255, 0, 0, 255))),
    frame(W, H, 0, 0, solid(W, H, (0, 255, 0, 255))),
]
open("default_image_not_a_frame.png", "wb").write(b.build(frames, default_image_scanlines=default_image))
PY

# ---------------------------------------------------------------------------
# 11: palette + tRNS. Two palette entries, one of them partially transparent,
# so EXPAND+ALPHA must turn indices into straight-alpha RGBA8.
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 2
palette = [(200, 20, 20), (20, 200, 20)]
alphas = [255, 100]  # index 0 opaque, index 1 semi-transparent
b = ApngBuilder(W, H, bit_depth=8, color_type=COLOR_INDEXED, palette=palette, trns_alphas=alphas)
frame0 = frame(W, H, 0, 0, [0, 1, 1, 0], encode=lambda idx, w, h: scanlines_indexed8(idx, w, h))
frame1 = frame(W, H, 0, 0, [1, 0, 0, 1], encode=lambda idx, w, h: scanlines_indexed8(idx, w, h))
open("palette_trns.png", "wb").write(b.build([frame0, frame1]))
PY

# ---------------------------------------------------------------------------
# 12: 16-bit RGBA. Each channel's high and low byte are deliberately
# different so STRIP_16 (truncate to the high byte) is distinguishable from
# rounding or taking the low byte.
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 2
b = ApngBuilder(W, H, bit_depth=16, color_type=COLOR_RGBA)
pixel16 = (0x1234, 0x5678, 0x9abc, 0xdef0)
frames = [
    frame(W, H, 0, 0, solid(W, H, pixel16), encode=scanlines_rgba16),
    frame(W, H, 0, 0, solid(W, H, (0x0102, 0x0304, 0x0506, 0xffff)), encode=scanlines_rgba16),
]
open("sixteen_bit.png", "wb").write(b.build(frames))
PY

# ---------------------------------------------------------------------------
# 13: truncated file. A syntactically-recognisable APNG (signature, IHDR,
# acTL, a leading fcTL) with NO IDAT at all — `read_until_image_data` hits
# EOF looking for the start of pixel data, which fails `probe`,
# `Animation::new` and `first_frame` alike with `Error::Malformed`.
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

W = H = 4
out = bytearray()
out += PNG_SIGNATURE
out += ihdr(W, H, 8, COLOR_RGBA)
out += actl(1, 1)
out += fctl(0, W, H, 0, 0, 1, 10, DISPOSE_NONE, BLEND_SOURCE)
# Deliberately no IDAT/IEND: the stream ends mid-header-walk.
open("truncated.png", "wb").write(bytes(out))
PY

# ---------------------------------------------------------------------------
# 14: an IHDR claiming a canvas above richimg's default pixel cap
# (16384x16384), with only a zero-length IDAT (no real pixel data) — the
# central pixel-cap check in `Animation::new` must refuse this from `probe`'s
# reported dimensions alone, before any canvas allocation.
# ---------------------------------------------------------------------------
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from apnglib import *

SIDE = 16384  # 2x richimg's default 8192 cap per side
out = bytearray()
out += PNG_SIGNATURE
out += ihdr(SIDE, SIDE, 8, COLOR_RGBA)
out += actl(1, 1)
out += fctl(0, SIDE, SIDE, 0, 0, 1, 10, DISPOSE_NONE, BLEND_SOURCE)
out += chunk(b"IDAT", b"")  # empty: never read once TooLarge is raised from `probe`'s dimensions
out += iend()
open("oversized_canvas.png", "wb").write(bytes(out))
PY

# ---------------------------------------------------------------------------
# Reference frames: raw straight-alpha RGBA8, one file per composited frame,
# decoded by ffmpeg's own (independent) APNG decoder, which composites
# dispose/blend internally before the rawvideo mux.
#
# No `magick` cross-check: verified (2026, ImageMagick 7.1.1-27, Q16-HDRI)
# that this installed build's PNG delegate does not decode APNG animation
# AT ALL, not just the default-image case — `magick x.png -coalesce` on an
# ordinary multi-frame fixture (`fcTL` before `IDAT`, no default image)
# still yields exactly one output file, holding only the leading frame's
# pixels. `identify` likewise reports one frame (no `x.png[0]`/`x.png[1]`)
# for such a file. So "cross-checked … against magick if it reads APNG"
# does not apply here: it doesn't. ffmpeg is the sole independent reference.
# ---------------------------------------------------------------------------
write_refs_ffmpeg() {
    local png_file="$1"
    local stem="$2"
    local width height frame_count
    width=$(python3 -c "import struct,sys; d=open(sys.argv[1],'rb').read(); print(struct.unpack('>I', d[16:20])[0])" "$png_file")
    height=$(python3 -c "import struct,sys; d=open(sys.argv[1],'rb').read(); print(struct.unpack('>I', d[20:24])[0])" "$png_file")
    # `-vsync 0`: pass every decoded frame straight through with no
    # duplication/drop to match a target frame rate. ffmpeg's `apng` demuxer
    # otherwise reports an absurd derived `tbr` for small hand-built fcTL
    # delays, and the default rawvideo fps behaviour then duplicates each
    # frame thousands of times to fill the animation's total duration.
    ffmpeg -nostdin -y -v error -vsync 0 -i "$png_file" -f rawvideo -pix_fmt rgba "${stem}.raw" </dev/null
    local frame_bytes=$((width * height * 4))
    local total_bytes
    total_bytes=$(stat -c%s "${stem}.raw")
    frame_count=$((total_bytes / frame_bytes))
    local i=0
    while [ "$i" -lt "$frame_count" ]; do
        dd if="${stem}.raw" of="${REFS_DIR}/${stem}-${i}.rgba" bs="$frame_bytes" skip="$i" count=1 status=none
        i=$((i + 1))
    done
}

write_refs_ffmpeg dispose_none.png dispose_none
write_refs_ffmpeg dispose_background.png dispose_background
write_refs_ffmpeg dispose_previous.png dispose_previous
write_refs_ffmpeg dispose_previous_first_frame.png dispose_previous_first_frame
write_refs_ffmpeg blend_source.png blend_source
write_refs_ffmpeg blend_over.png blend_over
write_refs_ffmpeg still.png still
write_refs_ffmpeg fractional_delays.png fractional_delays
write_refs_ffmpeg short_delays.png short_delays
write_refs_ffmpeg loop_finite.png loop_finite
write_refs_ffmpeg default_image_not_a_frame.png default_image_not_a_frame
write_refs_ffmpeg palette_trns.png palette_trns
write_refs_ffmpeg sixteen_bit.png sixteen_bit

# ---------------------------------------------------------------------------
# Install the generated fixtures over the committed ones.
# ---------------------------------------------------------------------------
for name in dispose_none dispose_background dispose_previous dispose_previous_first_frame \
            blend_source blend_over still fractional_delays short_delays loop_finite loop_infinite \
            default_image_not_a_frame palette_trns sixteen_bit truncated oversized_canvas; do
    cp "$WORK/$name.png" "$FIXTURES_DIR/$name.png"
done

echo "make_apng.sh: fixtures and reference frames written to $FIXTURES_DIR"
