//! Shared helpers for richimg's integration tests. Not a test target itself
//! (it lives under `tests/support/`, not directly in `tests/`), included via
//! `#[path = "support/mod.rs"] mod support;` in each file that needs it.
#![allow(dead_code)] // each test file uses a different subset of these helpers

use std::path::{Path, PathBuf};
use std::sync::Arc;

pub const RGBA_CHANNELS: usize = 4;

/// Per-channel tolerance for comparing richimg's decode against `magick
/// -coalesce`: YUV/blend rounding differences of up to 1 LSB are expected
/// and documented; a lossless, unblended fixture should in practice
/// come out exact, but the tolerance is not tightened per-fixture.
pub const CHANNEL_TOLERANCE: i16 = 1;

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

pub fn fixture_path(name: &str) -> PathBuf {
    fixtures_dir().join(name)
}

pub fn read_fixture(name: &str) -> Arc<[u8]> {
    let path = fixture_path(name);
    let bytes = std::fs::read(&path)
        .unwrap_or_else(|err| panic!("reading fixture {}: {err}", path.display()));
    Arc::from(bytes)
}

/// Reads a committed raw-RGBA reference frame (`tests/fixtures/refs/<stem>-<index>.rgba`).
pub fn read_ref_frame(stem: &str, index: u32) -> Vec<u8> {
    let path = fixtures_dir()
        .join("refs")
        .join(format!("{stem}-{index}.rgba"));
    std::fs::read(&path).unwrap_or_else(|err| panic!("reading reference {}: {err}", path.display()))
}

/// Reads a committed raw-RGBA reference frame from the APNG fixture set
/// (`tests/fixtures/apng/refs/<stem>-<index>.rgba`), generated by
/// `tests/fixtures/make_apng.sh` from ffmpeg's independent APNG decode.
pub fn read_apng_ref_frame(stem: &str, index: u32) -> Vec<u8> {
    let path = fixtures_dir()
        .join("apng/refs")
        .join(format!("{stem}-{index}.rgba"));
    std::fs::read(&path).unwrap_or_else(|err| panic!("reading reference {}: {err}", path.display()))
}

/// One excluded rectangle (in pixel coordinates, half-open `[x0,x1) x [y0,y1)`)
/// and which channels within it are skipped, for a fixture with a
/// documented, deliberate divergence from the `magick` reference (see
/// `richimg/src/webp.rs`'s dispose-to-background doc comment, and the
/// `partial_transparent` test module, for the two known cases).
pub struct Exclude {
    pub x0: u32,
    pub y0: u32,
    pub x1: u32,
    pub y1: u32,
    pub skip_rgb: bool,
    pub skip_alpha: bool,
}

/// Compares `actual` (a decoded `Frame::rgba`) against a committed reference
/// frame, channel by channel, within [`CHANNEL_TOLERANCE`] — except inside
/// any `exclusions`, whose named channels are not checked at all (they are
/// covered by a separate, explicit assertion elsewhere in the same test).
const ALPHA_CHANNEL: usize = 3;

pub fn assert_matches_reference(
    actual: &[u8],
    reference: &[u8],
    width: u32,
    height: u32,
    exclusions: &[Exclude],
    context: &str,
) {
    assert_eq!(
        actual.len(),
        reference.len(),
        "{context}: byte length mismatch"
    );
    assert_eq!(
        actual.len(),
        (width as usize) * (height as usize) * RGBA_CHANNELS,
        "{context}: length does not match width*height*4"
    );

    for y in 0..height {
        for x in 0..width {
            let pixel_index = ((y * width + x) as usize) * RGBA_CHANNELS;
            let excluded = exclusions
                .iter()
                .find(|e| x >= e.x0 && x < e.x1 && y >= e.y0 && y < e.y1);

            // Straight alpha: a pixel both sides call fully transparent has no
            // visible colour, so its RGB is not compared (magick keeps the prior
            // RGB under alpha 0; a zeroed clear writes 0,0,0).
            let both_transparent = actual[pixel_index + ALPHA_CHANNEL] == 0
                && reference[pixel_index + ALPHA_CHANNEL] == 0;
            for channel in 0..RGBA_CHANNELS {
                let is_alpha = channel == ALPHA_CHANNEL;
                if both_transparent && !is_alpha {
                    continue;
                }
                if let Some(exclusion) = excluded {
                    if (is_alpha && exclusion.skip_alpha) || (!is_alpha && exclusion.skip_rgb) {
                        continue;
                    }
                }
                let a = i16::from(actual[pixel_index + channel]);
                let b = i16::from(reference[pixel_index + channel]);
                assert!(
                    (a - b).abs() <= CHANNEL_TOLERANCE,
                    "{context}: pixel ({x},{y}) channel {channel} differs: actual={a} reference={b} (tolerance {CHANNEL_TOLERANCE})"
                );
            }
        }
    }
}

pub fn pixel(rgba: &[u8], width: u32, x: u32, y: u32) -> [u8; 4] {
    let idx = ((y * width + x) as usize) * RGBA_CHANNELS;
    [rgba[idx], rgba[idx + 1], rgba[idx + 2], rgba[idx + 3]]
}

// --- GIF additions below: the same scheme as the WebP helpers above,
// but GIF's fixtures and references live one directory down
// (`tests/fixtures/gif/` and `tests/fixtures/gif/refs/`, built by
// `make_gif.sh`) so they don't mix with the WebP fixtures.

pub fn gif_fixture_path(name: &str) -> PathBuf {
    fixtures_dir().join("gif").join(name)
}

pub fn read_gif_fixture(name: &str) -> Arc<[u8]> {
    let path = gif_fixture_path(name);
    std::fs::read(&path)
        .map(Arc::from)
        .unwrap_or_else(|err| panic!("reading fixture {}: {err}", path.display()))
}

/// Reads a committed raw-RGBA reference frame
/// (`tests/fixtures/gif/refs/<stem>-<index>.rgba`).
pub fn read_gif_ref_frame(stem: &str, index: u32) -> Vec<u8> {
    let path = fixtures_dir()
        .join("gif")
        .join("refs")
        .join(format!("{stem}-{index}.rgba"));
    std::fs::read(&path).unwrap_or_else(|err| panic!("reading reference {}: {err}", path.display()))
}
