//! Shared helpers for richimg's integration tests. Not a test target itself
//! (it lives under `tests/support/`, not directly in `tests/`), included via
//! `#[path = "support/mod.rs"] mod support;` in each file that needs it.
#![allow(dead_code)] // each test file uses a different subset of these helpers

use std::path::{Path, PathBuf};
use std::sync::Arc;

pub const RGBA_CHANNELS: usize = 4;

/// Per-channel tolerance for comparing richimg's decode against `magick
/// -coalesce`: YUV/blend rounding differences of up to 1 LSB are expected
/// and documented; a lossless, unblended fixture should in practice
/// come out exact, but the tolerance is not tightened per-fixture.
pub const CHANNEL_TOLERANCE: i16 = 1;

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

pub fn fixture_path(name: &str) -> PathBuf {
    fixtures_dir().join(name)
}

pub fn read_fixture(name: &str) -> Arc<[u8]> {
    let path = fixture_path(name);
    let bytes = std::fs::read(&path)
        .unwrap_or_else(|err| panic!("reading fixture {}: {err}", path.display()));
    Arc::from(bytes)
}

/// Reads a committed raw-RGBA reference frame (`tests/fixtures/refs/<stem>-<index>.rgba`).
pub fn read_ref_frame(stem: &str, index: u32) -> Vec<u8> {
    let path = fixtures_dir()
        .join("refs")
        .join(format!("{stem}-{index}.rgba"));
    std::fs::read(&path).unwrap_or_else(|err| panic!("reading reference {}: {err}", path.display()))
}

/// Reads a committed raw-RGBA reference frame from the APNG fixture set
/// (`tests/fixtures/apng/refs/<stem>-<index>.rgba`), generated by
/// `tests/fixtures/make_apng.sh` from ffmpeg's independent APNG decode.
pub fn read_apng_ref_frame(stem: &str, index: u32) -> Vec<u8> {
    let path = fixtures_dir()
        .join("apng/refs")
        .join(format!("{stem}-{index}.rgba"));
    std::fs::read(&path).unwrap_or_else(|err| panic!("reading reference {}: {err}", path.display()))
}

/// One excluded rectangle (in pixel coordinates, half-open `[x0,x1) x [y0,y1)`)
/// and which channels within it are skipped, for a fixture with a
/// documented, deliberate divergence from the `magick` reference (see
/// `richimg/src/webp.rs`'s dispose-to-background doc comment, and the
/// `partial_transparent` test module, for the two known cases).
pub struct Exclude {
    pub x0: u32,
    pub y0: u32,
    pub x1: u32,
    pub y1: u32,
    pub skip_rgb: bool,
    pub skip_alpha: bool,
}

/// Compares `actual` (a decoded `Frame::rgba`) against a committed reference
/// frame, channel by channel, within [`CHANNEL_TOLERANCE`] — except inside
/// any `exclusions`, whose named channels are not checked at all (they are
/// covered by a separate, explicit assertion elsewhere in the same test).
const ALPHA_CHANNEL: usize = 3;

pub fn assert_matches_reference(
    actual: &[u8],
    reference: &[u8],
    width: u32,
    height: u32,
    exclusions: &[Exclude],
    context: &str,
) {
    assert_eq!(
        actual.len(),
        reference.len(),
        "{context}: byte length mismatch"
    );
    assert_eq!(
        actual.len(),
        (width as usize) * (height as usize) * RGBA_CHANNELS,
        "{context}: length does not match width*height*4"
    );

    for y in 0..height {
        for x in 0..width {
            let pixel_index = ((y * width + x) as usize) * RGBA_CHANNELS;
            let excluded = exclusions
                .iter()
                .find(|e| x >= e.x0 && x < e.x1 && y >= e.y0 && y < e.y1);

            // Straight alpha: a pixel both sides call fully transparent has no
            // visible colour, so its RGB is not compared (magick keeps the prior
            // RGB under alpha 0; a zeroed clear writes 0,0,0).
            let both_transparent = actual[pixel_index + ALPHA_CHANNEL] == 0
                && reference[pixel_index + ALPHA_CHANNEL] == 0;
            for channel in 0..RGBA_CHANNELS {
                let is_alpha = channel == ALPHA_CHANNEL;
                if both_transparent && !is_alpha {
                    continue;
                }
                if let Some(exclusion) = excluded {
                    if (is_alpha && exclusion.skip_alpha) || (!is_alpha && exclusion.skip_rgb) {
                        continue;
                    }
                }
                let a = i16::from(actual[pixel_index + channel]);
                let b = i16::from(reference[pixel_index + channel]);
                assert!(
                    (a - b).abs() <= CHANNEL_TOLERANCE,
                    "{context}: pixel ({x},{y}) channel {channel} differs: actual={a} reference={b} (tolerance {CHANNEL_TOLERANCE})"
                );
            }
        }
    }
}

pub fn pixel(rgba: &[u8], width: u32, x: u32, y: u32) -> [u8; 4] {
    let idx = ((y * width + x) as usize) * RGBA_CHANNELS;
    [rgba[idx], rgba[idx + 1], rgba[idx + 2], rgba[idx + 3]]
}

// --- GIF additions below: the same scheme as the WebP helpers above,
// but GIF's fixtures and references live one directory down
// (`tests/fixtures/gif/` and `tests/fixtures/gif/refs/`, built by
// `make_gif.sh`) so they don't mix with the WebP fixtures.

pub fn gif_fixture_path(name: &str) -> PathBuf {
    fixtures_dir().join("gif").join(name)
}

pub fn read_gif_fixture(name: &str) -> Arc<[u8]> {
    let path = gif_fixture_path(name);
    std::fs::read(&path)
        .map(Arc::from)
        .unwrap_or_else(|err| panic!("reading fixture {}: {err}", path.display()))
}

/// Reads a committed raw-RGBA reference frame
/// (`tests/fixtures/gif/refs/<stem>-<index>.rgba`).
pub fn read_gif_ref_frame(stem: &str, index: u32) -> Vec<u8> {
    let path = fixtures_dir()
        .join("gif")
        .join("refs")
        .join(format!("{stem}-{index}.rgba"));
    std::fs::read(&path).unwrap_or_else(|err| panic!("reading reference {}: {err}", path.display()))
}

// ── the counting allocator, shared by the three no-oversized-alloc targets ────

/// A `#[global_allocator]` that records the LARGEST single allocation request the
/// process has made.
///
/// **Why the three targets are three BINARIES and one implementation.** Only one
/// `#[global_allocator]` may exist per binary, and this one instruments every
/// allocation the whole process makes — so sharing a binary between these tests and
/// any other richimg test would make "no huge allocation happened" depend on whatever
/// else ran there. That argument is about needing three *binaries*. It was taken as an
/// argument for three copies of the *body*, and the copies then drifted.
///
/// Each target keeps only its own `#[global_allocator]` line, its fixture and its
/// assertions:
///
/// ```ignore
/// #[global_allocator]
/// static ALLOCATOR: support::CountingAllocator = support::CountingAllocator;
/// ```
pub struct CountingAllocator;

/// The largest single allocation request seen since the last [`reset_largest_allocation`].
pub static LARGEST_ALLOCATION: std::sync::atomic::AtomicUsize =
    std::sync::atomic::AtomicUsize::new(0);

/// A canvas for a 16384x16384 RGBA claim would be 1,073,741,824 bytes. This threshold
/// sits two orders of magnitude below that: generous enough never to trip on the small
/// allocations a decoder legitimately makes (`Vec` growth, its own bookkeeping), and
/// far below anything canvas-sized.
pub const MAX_LEGITIMATE_ALLOCATION_BYTES: usize = 1024 * 1024;

unsafe impl std::alloc::GlobalAlloc for CountingAllocator {
    unsafe fn alloc(&self, layout: std::alloc::Layout) -> *mut u8 {
        LARGEST_ALLOCATION.fetch_max(layout.size(), std::sync::atomic::Ordering::SeqCst);
        std::alloc::System.alloc(layout)
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: std::alloc::Layout) {
        std::alloc::System.dealloc(ptr, layout)
    }

    unsafe fn realloc(&self, ptr: *mut u8, layout: std::alloc::Layout, new_size: usize) -> *mut u8 {
        LARGEST_ALLOCATION.fetch_max(new_size, std::sync::atomic::Ordering::SeqCst);
        std::alloc::System.realloc(ptr, layout, new_size)
    }
}

/// Serialises every measurement in the binary.
///
/// The counter is PROCESS-global — that is the whole point of a `#[global_allocator]`
/// — and libtest runs a binary's tests in parallel threads, so two measurements in
/// flight at once read each other's allocations and each other's resets. The tests in
/// these targets shared one counter with no lock, and it was the positive control that
/// exposed it: the control allocated four megabytes and then read a counter another
/// test had zeroed in between, so the instrument looked dark when it was merely being
/// trampled.
///
/// Every measured region takes this for its whole duration — hence [`measured`] rather
/// than a bare reset, so there is no way to start a region without holding it.
static MEASUREMENT: std::sync::Mutex<()> = std::sync::Mutex::new(());

/// Run `f` as the binary's only measurement, with the counter zeroed first.
///
/// Poisoning is ignored deliberately: a panicking assertion inside one measured region
/// must not turn every later one into a second, misleading failure.
pub fn measured<R>(f: impl FnOnce() -> R) -> R {
    let _lock = MEASUREMENT.lock().unwrap_or_else(|e| e.into_inner());
    reset_largest_allocation();
    f()
}

/// Zero the counter before a measured region. Prefer [`measured`], which cannot be
/// called without holding the lock.
pub fn reset_largest_allocation() {
    LARGEST_ALLOCATION.store(0, std::sync::atomic::Ordering::SeqCst);
}

/// The counter's current value.
pub fn largest_allocation() -> usize {
    LARGEST_ALLOCATION.load(std::sync::atomic::Ordering::SeqCst)
}

/// Run `f` and assert nothing canvas-sized was allocated while it ran.
///
/// **The measurement and the reading happen under ONE hold of the lock, and that is the
/// whole point of this function existing.** The counter is process-global — there is one
/// `#[global_allocator]` per binary — while libtest runs a binary's cases on several
/// threads at once, so any window between `f` returning and the counter being read is a
/// window in which another case's allocations land in it.
///
/// That window was real. The pattern here used to be `measured(|| …)` followed by a
/// separate assertion, which takes the lock, resets, measures, and then **drops the
/// lock** at the end of the statement — leaving the read unprotected. MEASURED: a
/// pipeline run failed with *"probe() allocated 4194304 bytes"*, which is exactly
/// `MAX_LEGITIMATE_ALLOCATION_BYTES * 4`, the deliberate allocation made by the sibling
/// positive control in the same binary. `probe` had allocated nothing of the kind.
///
/// **The false failure is the harmless direction.** The same window lets a sibling's
/// `reset_largest_allocation` zero the counter between a real oversized allocation and
/// the read — an absence assertion passing because nobody was counting. That direction
/// is silent, and it is what makes this a correctness fix to a gate rather than a flake
/// to be re-run.
pub fn measured_no_canvas_sized_allocation<R>(what: &str, f: impl FnOnce() -> R) -> R {
    let _lock = MEASUREMENT.lock().unwrap_or_else(|e| e.into_inner());
    reset_largest_allocation();
    let out = f();
    let seen = largest_allocation();
    assert!(
        seen < MAX_LEGITIMATE_ALLOCATION_BYTES,
        "{what} allocated {seen} bytes in a single request, over the \
         {MAX_LEGITIMATE_ALLOCATION_BYTES}-byte threshold"
    );
    out
}

/// **The positive control for the instrument itself.**
///
/// Every assertion above is an ABSENCE — "no allocation over the threshold happened" —
/// and an absence proves nothing until the instrument has been shown capable of
/// reporting a presence. Neuter `fetch_max` and every one of those assertions passes,
/// in all three binaries, along with their fixture controls: the decode still works,
/// the refusals still refuse, and the counter simply never moves.
///
/// So each target calls this: allocate something unmistakably canvas-sized, and require
/// the counter to have seen it. Now a dead counter is a failure rather than a pass.
pub fn assert_the_counter_can_see_a_large_allocation() {
    let big = MAX_LEGITIMATE_ALLOCATION_BYTES * 4;
    let seen = measured(|| {
        // `black_box` on both sides: the allocation must survive optimisation, and so
        // must the read, or the control can be compiled away into a vacuous pass.
        let v: Vec<u8> = Vec::with_capacity(big);
        std::hint::black_box(&v);
        largest_allocation()
    });
    assert!(
        seen >= big,
        "the counting allocator did not observe a deliberate {big}-byte allocation \
         (largest seen: {seen}) — the instrument is dark, so every 'nothing large was \
         allocated' assertion in this binary is vacuous"
    );
}
